using System;
using System.Data;

using RAD.AppFramework.Data;

using amlak.Common;
using amlak.DataAccess.Adapters.Base;

namespace amlak.DataAccess.Adapters
{
	/// <summary>
	/// divar_dakli_glbDataAdapter allows for application specific data operations to be added without 
	/// having to make changes to the auto-generated divar_dakli_glbDataAdapterBase class. 
	/// <seealso cref="divar_dakli_glbDataAdapterBase"/>
	/// </summary>
	/// <remarks>
	/// Any modifications must be made to the divar_dakli_glbDataAdapter class.
	/// <br/><br/>
	/// This class was automatically generated by Rad Software NextGeneration <a href="http://www.radsoftware.com.au">http://www.radsoftware.com.au</a>
	/// </remarks>
	public class divar_dakli_glbDataAdapter : divar_dakli_glbDataAdapterBase
	{
		#region Constants
		
		
		
		#endregion
		
		
		#region Fields
		
		/// <summary>
		/// A static instance of the divar_dakli_glbDataAdapter
		/// </summary>
		static divar_dakli_glbDataAdapter m_Instance;		
		
		#endregion
		
		
		#region Constructors
		
		/// <summary>
		/// Creates a new divar_dakli_glbDataAdapter 
		/// that uses the specified DatabaseConnection
		/// </summary>
		public divar_dakli_glbDataAdapter(DatabaseConnection dbconnection) : base(dbconnection)
		{
		
		}
		
		/// <summary>
		/// Creates a new divar_dakli_glbDataAdapter 
		/// </summary>
		public divar_dakli_glbDataAdapter() : base()
		{
		
		}
		
		/// <summary>
		/// Initializes the static instance
		/// </summary>
		static divar_dakli_glbDataAdapter()
		{
			m_Instance = new divar_dakli_glbDataAdapter();
		}
		
		#endregion
		
		
		#region Public Properties
		
		/// <summary>
		/// A default instance of the divar_dakli_glbDataAdapter
		/// </summary>
		public static divar_dakli_glbDataAdapter Instance
		{
			get { return m_Instance; }
		}		
		
		#endregion
		
		
		#region Private Methods
		
		
		
		#endregion
		
		
		#region Public Methods
		
		
		
		#endregion
	}
}
