using System;
using System.Data;

using RAD.AppFramework.Data;

using amlak.Common;
using amlak.DataAccess.Adapters.Base;

namespace amlak.DataAccess.Adapters
{
	/// <summary>
	/// noeDataAdapter allows for application specific data operations to be added without 
	/// having to make changes to the auto-generated noeDataAdapterBase class. 
	/// <seealso cref="noeDataAdapterBase"/>
	/// </summary>
	/// <remarks>
	/// Any modifications must be made to the noeDataAdapter class.
	/// <br/><br/>
	/// This class was automatically generated by Rad Software NextGeneration <a href="http://www.radsoftware.com.au">http://www.radsoftware.com.au</a>
	/// </remarks>
	public class noeDataAdapter : noeDataAdapterBase
	{
		#region Constants
		
		
		
		#endregion
		
		
		#region Fields
		
		/// <summary>
		/// A static instance of the noeDataAdapter
		/// </summary>
		static noeDataAdapter m_Instance;		
		
		#endregion
		
		
		#region Constructors
		
		/// <summary>
		/// Creates a new noeDataAdapter 
		/// that uses the specified DatabaseConnection
		/// </summary>
		public noeDataAdapter(DatabaseConnection dbconnection) : base(dbconnection)
		{
		
		}
		
		/// <summary>
		/// Creates a new noeDataAdapter 
		/// </summary>
		public noeDataAdapter() : base()
		{
		
		}
		
		/// <summary>
		/// Initializes the static instance
		/// </summary>
		static noeDataAdapter()
		{
			m_Instance = new noeDataAdapter();
		}
		
		#endregion
		
		
		#region Public Properties
		
		/// <summary>
		/// A default instance of the noeDataAdapter
		/// </summary>
		public static noeDataAdapter Instance
		{
			get { return m_Instance; }
		}		
		
		#endregion
		
		
		#region Private Methods
		
		
		
		#endregion
		
		
		#region Public Methods
		
		
		
		#endregion
	}
}
