using System;
using System.Data;

using RAD.AppFramework.Data;

using amlak.Common;
using amlak.DataAccess.Adapters.Base;

namespace amlak.DataAccess.Adapters
{
	/// <summary>
	/// sazehDataAdapter allows for application specific data operations to be added without 
	/// having to make changes to the auto-generated sazehDataAdapterBase class. 
	/// <seealso cref="sazehDataAdapterBase"/>
	/// </summary>
	/// <remarks>
	/// Any modifications must be made to the sazehDataAdapter class.
	/// <br/><br/>
	/// This class was automatically generated by Rad Software NextGeneration <a href="http://www.radsoftware.com.au">http://www.radsoftware.com.au</a>
	/// </remarks>
	public class sazehDataAdapter : sazehDataAdapterBase
	{
		#region Constants
		
		
		
		#endregion
		
		
		#region Fields
		
		/// <summary>
		/// A static instance of the sazehDataAdapter
		/// </summary>
		static sazehDataAdapter m_Instance;		
		
		#endregion
		
		
		#region Constructors
		
		/// <summary>
		/// Creates a new sazehDataAdapter 
		/// that uses the specified DatabaseConnection
		/// </summary>
		public sazehDataAdapter(DatabaseConnection dbconnection) : base(dbconnection)
		{
		
		}
		
		/// <summary>
		/// Creates a new sazehDataAdapter 
		/// </summary>
		public sazehDataAdapter() : base()
		{
		
		}
		
		/// <summary>
		/// Initializes the static instance
		/// </summary>
		static sazehDataAdapter()
		{
			m_Instance = new sazehDataAdapter();
		}
		
		#endregion
		
		
		#region Public Properties
		
		/// <summary>
		/// A default instance of the sazehDataAdapter
		/// </summary>
		public static sazehDataAdapter Instance
		{
			get { return m_Instance; }
		}		
		
		#endregion
		
		
		#region Private Methods
		
		
		
		#endregion
		
		
		#region Public Methods
		
		
		
		#endregion
	}
}
