using System;
using System.Data;

using RAD.AppFramework;
using RAD.AppFramework.Data;
using RAD.AppFramework.QueryObjects;

using amlak.Common;
using amlak.DatabaseSchema;
using amlak.Data;
using amlak.DataAccess.Adapters;
using amlak.BusinessService.Base;

namespace amlak.BusinessService
{
	/// <summary>
	/// sazehService allows for application specific business logic to be added without 
	/// having to make changes to the auto-generated sazehServiceBase class. 
	/// </summary>
	/// <remarks>
	/// Any additional functionality must be added to the sazehService class.
	/// <br/><br/>
	/// This class was automatically generated by Rad Software NextGeneration <a href="http://www.radsoftware.com.au">http://www.radsoftware.com.au</a>
	/// </remarks>
	public class sazehService : sazehServiceBase
	{
		#region Constants
		
		
		
		#endregion
		
		
		#region Fields
		
		/// <summary>
		/// A static instance of the sazehService
		/// </summary>
		static sazehService m_Instance;
		
		#endregion
		
		
		#region Constructors
		
		/// <summary>
		/// Creates a new sazehService
		/// </summary>
		public sazehService() : base()
		{
		}
		
		/// <summary>
		/// Creates a new sazehService and specifies the Database context
		/// </summary>		
		public sazehService(DatabaseConnection connection) : base(connection)
		{
		}
				
		/// <summary>
		/// Initializes the static instance
		/// </summary>
		static sazehService()
		{
			m_Instance = new sazehService();
		}
		
		#endregion
		
		
		#region Public Properties
		
		/// <summary>
		/// A default instance of the sazehService
		/// </summary>
		public static sazehService Instance
		{
			get { return m_Instance; }
		}
		
		#endregion
		
		
		#region Private Methods
		
		
		
		#endregion
		
		
		#region Public Methods
		
		
		
		#endregion
	}
}
