using System;
using System.Collections;
using System.Data;
using System.Data.Common;

using RAD.AppFramework.QueryObjects;

using amlak.Common;
using amlak.DatabaseSchema;
using amlak.DataAccess.Readers.Base;

namespace amlak.DataAccess.Readers
{
	/// <summary>
	/// Provides forward-only read access to the divar_dakli_glb table.
	/// <seealso cref="divar_dakli_glbDataReaderBase"/>
	/// </summary>
	/// <remarks>
	/// This class was automatically generated by Rad Software NextGeneration <a href="http://www.radsoftware.com.au">http://www.radsoftware.com.au</a>
	/// </remarks>
	public class divar_dakli_glbDataReader : divar_dakli_glbDataReaderBase
	{
		#region Constants
		
		
		
		#endregion
		
		
		#region Fields
		
		
		
		#endregion
		
		
		#region Constructors
		
		/// <summary>
		/// Creates a new divar_dakli_glbDataReader
		/// </summary>
		public divar_dakli_glbDataReader() : base()
		{
		
		}
		
		#endregion
		
		
		#region Public Properties
		

		
		#endregion
		
		
		#region Private Methods
		
		
		
		#endregion
		
		
		#region Public Methods
		
		
		
		#endregion

	}
}
