using System;
using System.Data;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.Collections;

using RAD.AppFramework.Data;
using RAD.AppFramework.QueryObjects;

using amlak.Common;
using amlak.DataAccess;

namespace amlak.DataAccess.Readers.Base
{
	/// <summary>
	/// Base class for the noeDataReader
	/// <seealso cref="noeDataReader"/>
	/// </summary>
	/// <remarks>
	/// Provides forward-only read access to the noe table.
	/// 
	/// This class has been auto-generated and should not be modified. Any modifications should
	/// be made to the <see cref="noeDataReader">noeDataReader</see> class.
	/// <br/><br/>
	/// This class was automatically generated by Rad Software NextGeneration <a href="http://www.radsoftware.com.au">http://www.radsoftware.com.au</a>
	/// </remarks>
	public class noeDataReaderBase : StronglyTypedDataReader
	{		
		#region Fields
	
		/// <summary>The ordinal position of the noe_id column in the result set</summary>
		protected int m_noe_idOrdinal;
		/// <summary>The ordinal position of the noe_nam column in the result set</summary>
		protected int m_noe_namOrdinal;
		/// <summary>The ordinal position of the noe_cls column in the result set</summary>
		protected int m_noe_clsOrdinal;
		/// <summary>The ordinal position of the noe_tozi column in the result set</summary>
		protected int m_noe_toziOrdinal;
			
		#endregion
		
		
		#region Constructors
		
		/// <summary>
		/// Creates a new noeDataReaderBase
		/// </summary>
		public noeDataReaderBase()
		{
			DatabaseAccessObjectFactory DataObjectFactory = CommonFactory.CreateDataObjectFactory();
		
			Connection = DataObjectFactory.CreateConnection();
		}
		
		#endregion
		

		#region Column Attributes


		/// <summary>
		/// Returns the value of the noe_id column for the current row
		/// </summary>
		public Int32 noe_id
		{
			get 
			{
					return (Int32)DataRecord[m_noe_idOrdinal];
			}
		}
	
		/// <summary>
		/// Returns the value of the noe_nam column for the current row
		/// </summary>
		public String noe_nam
		{
			get 
			{
					return (String)DataRecord[m_noe_namOrdinal];
			}
		}
	
		/// <summary>
		/// Returns the value of the noe_cls column for the current row
		/// </summary>
		public String noe_cls
		{
			get 
			{
					return (String)DataRecord[m_noe_clsOrdinal];
			}
		}
	
		/// <summary>
		/// Returns the value of the noe_tozi column for the current row
		/// </summary>
		public String noe_tozi
		{
			get 
			{
					return (String)DataRecord[m_noe_toziOrdinal];
			}
		}
	

		#endregion

		
		#region Private Methods
		
		/// <summary>
		/// Sets the indexes of the columns within the result set
		/// </summary>
		protected override void SetColumnOrdinals()
		{
			m_noe_idOrdinal = DataReader.GetOrdinal("noe_id");
			m_noe_namOrdinal = DataReader.GetOrdinal("noe_nam");
			m_noe_clsOrdinal = DataReader.GetOrdinal("noe_cls");
			m_noe_toziOrdinal = DataReader.GetOrdinal("noe_tozi");
		}
		
		#endregion
		
		
		#region Public Methods
		
		/// <summary>
		/// Selects all rows from the noe table
		/// </summary>
		/// <returns>true on success, false otherwise</returns>
		public bool SelectAll()
		{
			DatabaseAccessObjectFactory DataObjectFactory = CommonFactory.CreateDataObjectFactory();
		
			CommandSelect = DataObjectFactory.CreateCommand(Connection, CommandType.StoredProcedure);
			CommandSelect.CommandText = "gp_noe_SelectAll";
			
			return OpenReader();
		}
		
		/// <summary>
		/// Selects rows from the noe table by Query definion
		/// </summary>
		/// <param name="queryDefinition">A Query object that defines the Query used to select rows from the database</param>
		/// <returns>true on success, false otherwise</returns>
		public bool SelectByQuery(Query queryDefinition)
		{
			DatabaseAccessObjectFactory DataObjectFactory = CommonFactory.CreateDataObjectFactory();

			CommandSelect = DataObjectFactory.CreateCommand(Connection, CommandType.Text);

			if (queryDefinition.TableName.Length == 0)
			{
				queryDefinition.TableName = "gv_noe";
			}

			queryDefinition.BuildCommand(CommandSelect);

			return OpenReader();
		}
		
		
		/// <summary>
		/// Selects rows from the noe table by Primary Key (noe_id)
		/// </summary>
		/// <param name="noe_id">The noe_id to use as search criteria</param>
		/// <returns>true on success, false otherwise</returns>
		public bool SelectBynoe_id(Int32 noe_id)
		{
			DatabaseAccessObjectFactory DataObjectFactory = CommonFactory.CreateDataObjectFactory();
		
			CommandSelect = DataObjectFactory.CreateCommand(Connection, CommandType.StoredProcedure);
			CommandSelect.CommandText = "gp_noe_SelectBynoe_id";
			
			CommandSelect.Parameters.Add(DataObjectFactory.CreateCommandParameter("@noe_id", SqlDbType.Int, noe_id));
			
			return OpenReader();
		}
		
		
		
		
		#endregion
	}
}
