using System;
using System.Data;
using System.Data.Common;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.ComponentModel;

using amlak.Common;

using RAD.AppFramework.Data;
using RAD.AppFramework.QueryObjects;

namespace amlak.DataAccess.Adapters.Base
{
	/// <summary>
	/// sazehDataAdapterBase handles SELECT, INSERT, UPDATE and DELETE operations 
	/// for the sazeh table. 
	/// <seealso cref="sazehDataAdapter"/>
	/// </summary>
	/// <remarks>
	/// Do not make modifications to this class. Any additional functionality for the sazeh table 
	/// must be added to the sazehDataAdapter class.
	/// <br/><br/>
	/// This class was automatically generated by Rad Software NextGeneration <a href="http://www.radsoftware.com.au">http://www.radsoftware.com.au</a>
	/// </remarks>
	public abstract class sazehDataAdapterBase : DataAccessObject
	{
		#region Fields
		
		/// <summary>
		/// The name of the stored procedure that is used to retrieve rows from the sazeh table by primary key
		/// </summary>
		protected string SelectByszh_idCommandName = "gp_sazeh_SelectByszh_id";
		
		/// <summary>
		/// The stored procedure used to retrieve rows based on the relationship to the noe table 
		/// </summary>
		protected string SelectByfndsion_noe_idCommandName = "gp_sazeh_SelectByfndsion_noe_id";
					
		/// <summary>
		/// The stored procedure used to retrieve rows based on the relationship to the noe table 
		/// </summary>
		protected string SelectBysgf_noe_idCommandName = "gp_sazeh_SelectBysgf_noe_id";
					
		/// <summary>
		/// The stored procedure used to retrieve rows based on the relationship to the noe table 
		/// </summary>
		protected string SelectBysklt_noe_idCommandName = "gp_sazeh_SelectBysklt_noe_id";
					
		/// <summary>
		/// The stored procedure used to retrieve rows based on the relationship to the noe table 
		/// </summary>
		protected string SelectBydivar_karji_glb_idCommandName = "gp_sazeh_SelectBydivar_karji_glb_id";
					

		#endregion
		
		
		#region Constructors
		
		/// <summary>
		/// Creates a new sazehDataAdapterBase 
		/// that uses the specified DatabaseConnection
		/// </summary>
		protected sazehDataAdapterBase(DatabaseConnection dbconnection) : this()
		{
			UseConnectionAndTransaction(dbconnection);
		}
		
		
		/// <summary>
		/// Creates a new sazehDataAdapterBase 
		/// </summary>
		public sazehDataAdapterBase() : base()
		{
			InsertCommandName = "gp_sazeh_Insert";
			UpdateCommandName = "gp_sazeh_Update";
			DeleteCommandName = "gp_sazeh_Delete";
			SelectAllCommandName = "gp_sazeh_SelectAll";
		
			//
			// Map the default table name of "Table" to the strongly typed DataTable 
			//
			Adapter.TableMappings.Add("Table", "sazeh");
			
			
		}
		
		
		#endregion
		
		
		#region Private Methods
		
		
		/// <summary>
		/// Creates an instance of a factory that is used to create Database objects
		/// </summary>
		/// <returns>A DatabaseAccessObjectFactory instance </returns>
		protected override DatabaseAccessObjectFactory CreateDataObjectFactory()
		{
			return CommonFactory.CreateDataObjectFactory();
		}
		

		/// <summary>
		/// Adds parameters representing the columns in the  
		/// new row to the Insert Command
		/// </summary>
		/// <param name="insertCommand">The command to add the parameters to</param>
		protected override void AddInsertCommandParameters(IDbCommand insertCommand)
		{
			base.AddInsertCommandParameters(insertCommand);
			
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@szh_id", "szh_id", SqlDbType.Int));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@mlk_id", "mlk_id", SqlDbType.Int));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@rsht_id", "rsht_id", SqlDbType.Int));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@modirt_id", "modirt_id", SqlDbType.Int));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@shrstan_id", "shrstan_id", SqlDbType.Int));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@shobh_id", "shobh_id", SqlDbType.NChar, 10));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@fndsion_noe_id", "fndsion_noe_id", SqlDbType.Int));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@fndsion_tozi", "fndsion_tozi", SqlDbType.VarChar));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@sgf_noe_id", "sgf_noe_id", SqlDbType.Int));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@sgf_sayr", "sgf_sayr", SqlDbType.VarChar, 200));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@sgf_tozi", "sgf_tozi", SqlDbType.VarChar));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@sklt_noe_id", "sklt_noe_id", SqlDbType.Int));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@sklt_tozi", "sklt_tozi", SqlDbType.VarChar, 200));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@sklt_sayr", "sklt_sayr", SqlDbType.VarChar));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@divar_karji_glb_id", "divar_karji_glb_id", SqlDbType.Int));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@divar_dakli_glb_partition", "divar_dakli_glb_partition", SqlDbType.Bit));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@divar_dakli_glb_simani", "divar_dakli_glb_simani", SqlDbType.Bit));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@divar_dakli_glb_lika", "divar_dakli_glb_lika", SqlDbType.Bit));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@divar_dakli_glb_hblx", "divar_dakli_glb_hblx", SqlDbType.Bit));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@divar_dakli_glb_sofali", "divar_dakli_glb_sofali", SqlDbType.Bit));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@divar_dakli_glb_poma", "divar_dakli_glb_poma", SqlDbType.Bit));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@divar_dakli_glb_ajor", "divar_dakli_glb_ajor", SqlDbType.Bit));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@divar_dakli_glb_drywall", "divar_dakli_glb_drywall", SqlDbType.Bit));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@divar_dakli_glb_sayer", "divar_dakli_glb_sayer", SqlDbType.Bit));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@divar_dakli_glb_sayer_val", "divar_dakli_glb_sayer_val", SqlDbType.NVarChar, 200));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@divar_dakli_glb_tozi", "divar_dakli_glb_tozi", SqlDbType.Int));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@thvil_tarikh", "thvil_tarikh", SqlDbType.Char, 10));
			insertCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@thvil_krshnas", "thvil_krshnas", SqlDbType.Int));
			
		}
		

		/// <summary>
		/// Adds parameters representing the columns in the 
		/// updated row to the Update Command
		/// </summary>
		/// <param name="updateCommand">The Command to add the parameters to</param>
		protected override void AddUpdateCommandParameters(IDbCommand updateCommand)
		{
			base.AddUpdateCommandParameters(updateCommand);
			
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@szh_idOriginal", "szh_id", SqlDbType.Int, DataRowVersion.Original));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@szh_id", "szh_id", SqlDbType.Int));
			
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@mlk_id", "mlk_id", SqlDbType.Int));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@rsht_id", "rsht_id", SqlDbType.Int));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@modirt_id", "modirt_id", SqlDbType.Int));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@shrstan_id", "shrstan_id", SqlDbType.Int));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@shobh_id", "shobh_id", SqlDbType.NChar, 10));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@fndsion_noe_id", "fndsion_noe_id", SqlDbType.Int));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@fndsion_tozi", "fndsion_tozi", SqlDbType.VarChar));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@sgf_noe_id", "sgf_noe_id", SqlDbType.Int));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@sgf_sayr", "sgf_sayr", SqlDbType.VarChar, 200));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@sgf_tozi", "sgf_tozi", SqlDbType.VarChar));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@sklt_noe_id", "sklt_noe_id", SqlDbType.Int));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@sklt_tozi", "sklt_tozi", SqlDbType.VarChar, 200));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@sklt_sayr", "sklt_sayr", SqlDbType.VarChar));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@divar_karji_glb_id", "divar_karji_glb_id", SqlDbType.Int));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@divar_dakli_glb_partition", "divar_dakli_glb_partition", SqlDbType.Bit));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@divar_dakli_glb_simani", "divar_dakli_glb_simani", SqlDbType.Bit));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@divar_dakli_glb_lika", "divar_dakli_glb_lika", SqlDbType.Bit));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@divar_dakli_glb_hblx", "divar_dakli_glb_hblx", SqlDbType.Bit));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@divar_dakli_glb_sofali", "divar_dakli_glb_sofali", SqlDbType.Bit));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@divar_dakli_glb_poma", "divar_dakli_glb_poma", SqlDbType.Bit));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@divar_dakli_glb_ajor", "divar_dakli_glb_ajor", SqlDbType.Bit));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@divar_dakli_glb_drywall", "divar_dakli_glb_drywall", SqlDbType.Bit));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@divar_dakli_glb_sayer", "divar_dakli_glb_sayer", SqlDbType.Bit));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@divar_dakli_glb_sayer_val", "divar_dakli_glb_sayer_val", SqlDbType.NVarChar, 200));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@divar_dakli_glb_tozi", "divar_dakli_glb_tozi", SqlDbType.Int));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@thvil_tarikh", "thvil_tarikh", SqlDbType.Char, 10));
			updateCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@thvil_krshnas", "thvil_krshnas", SqlDbType.Int));
			
		}
		

		/// <summary>
		/// Adds parameters representing the columns in the
		/// deleted row to the Delete Command
		/// </summary>
		/// <param name="deleteCommand">The Command to add the parameters to</param>
		protected override void AddDeleteCommandParameters(IDbCommand deleteCommand)
		{
			base.AddDeleteCommandParameters(deleteCommand);
			
			deleteCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@szh_id", "szh_id", SqlDbType.Int));
			
		}

		
		#endregion
		
		
		#region Public Methods
		
		/// <summary>
		/// Calls the respective INSERT, UPDATE, or DELETE statements 
		/// for each inserted, updated, or deleted row in the specified DataSet
		/// </summary>
		/// <param name="dataSetUpdate">The DataSet used to update the data source</param>
		/// <returns>The number of rows successfully updated from the DataSet</returns>
		public override int Update(DataSet dataSetUpdate)
		{
			int baseCount = base.Update(dataSetUpdate);
			
			if (AdapterCommands.InsertCommand == null)
			{
				//
				// Open the Database Connection 
				//
				DbConnection.Open();

				//
				// Insert Command
				//
				IDbCommand InsertCommand = DataObjectFactory.CreateCommand(DbConnection, CommandType.StoredProcedure);
				InsertCommand.CommandText = InsertCommandName;
				InsertCommand.UpdatedRowSource = UpdateRowSource.FirstReturnedRecord;
				AddInsertCommandParameters(InsertCommand);
				AdapterCommands.InsertCommand = InsertCommand;

				//
				// Update Command
				//
				IDbCommand UpdateCommand = DataObjectFactory.CreateCommand(DbConnection, CommandType.StoredProcedure);
				UpdateCommand.CommandText = UpdateCommandName;
				UpdateCommand.UpdatedRowSource = UpdateRowSource.FirstReturnedRecord;
				AddUpdateCommandParameters(UpdateCommand);
				AdapterCommands.UpdateCommand = UpdateCommand;

				//
				// Delete Command
				//
				IDbCommand DeleteCommand = DataObjectFactory.CreateCommand(DbConnection, CommandType.StoredProcedure);
				DeleteCommand.CommandText = DeleteCommandName;
				AddDeleteCommandParameters(DeleteCommand);
				AdapterCommands.DeleteCommand = DeleteCommand;
			}
			else
			{
				//
				// DataAdapter and Command objects have already been created
				// make sure the current connection and transaction are being used
				//
				DbConnection.Open();
				
				AdapterCommands.InsertCommand.Connection = DbConnection.Connection;
				AdapterCommands.InsertCommand.Transaction = DbConnection.Transaction;

				AdapterCommands.UpdateCommand.Connection = DbConnection.Connection;
				AdapterCommands.UpdateCommand.Transaction = DbConnection.Transaction;

				AdapterCommands.DeleteCommand.Connection = DbConnection.Connection;
				AdapterCommands.DeleteCommand.Transaction = DbConnection.Transaction;
			}

			//
			// Apply the changes in the DataSet and return the number of affected rows
			//
			try
			{
				return baseCount + Adapter.Update(dataSetUpdate);
			}
			finally
			{
				DbConnection.Close();
			}
		}
		
		
		/// <summary>
		/// Fill the DataSet with all rows from the sazeh Table
		/// </summary>
		/// <param name="dataSetFill">The DataSet to fill</param>
		/// <returns>A count of the rows added to the DataSet</returns>
		public override int Fill(DataSet dataSetFill)
		{
			int baseCount = base.Fill(dataSetFill);
			
			IDbCommand FillCommand = DataObjectFactory.CreateCommand(DbConnection, CommandType.StoredProcedure);

			FillCommand.CommandText = SelectAllCommandName;
			
			return baseCount + LoadFromCommand(dataSetFill, FillCommand);
		}
		
		
		/// <summary>
		/// Fill the DataSet by Query Definition
		/// </summary>
		/// <param name="dataSetFill">The DataSet to fill</param>
		/// <param name="queryDefinition">An Query object that defines the the query</param>
		/// <returns>A count of the rows added to the DataSet</returns>
		public override int FillByQuery(DataSet dataSetFill, Query queryDefinition)
		{
			if (queryDefinition == null)
			{
				throw new ArgumentNullException("queryDefinition");
			}

			IDbCommand FillCommand = DataObjectFactory.CreateCommand(DbConnection, CommandType.Text);

			if (queryDefinition.TableName.Length == 0)
			{
				queryDefinition.TableName = "gv_sazeh";
			}

			queryDefinition.BuildCommand(FillCommand);
			
			return LoadFromCommand(dataSetFill, FillCommand);
		}

		
		
		/// <summary>
		/// Fill the DataSet with all rows from the sazeh Table by Primary key (szh_id)
		/// </summary>
		/// <param name="dataSetFill">The DataSet to fill</param>
		/// <param name="szh_id">The szh_id to use as search criteria</param>
		/// <returns>A count of the rows added to the DataSet</returns>
		public int FillByszh_id(DataSet dataSetFill, Int32 szh_id)
		{
			IDbCommand FillCommand = DataObjectFactory.CreateCommand(DbConnection, CommandType.StoredProcedure);

			FillCommand.CommandText = SelectByszh_idCommandName;

			FillCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@szh_id", SqlDbType.Int, szh_id));
			
			return LoadFromCommand(dataSetFill, FillCommand);
		}	


		/// <summary>
		/// Fill the DataSet with rows from the sazeh table that match the specified fndsion_noe_id
		/// </summary>
		/// <param name="dataSetFill">The DataSet to fill</param>
		/// <param name="fndsion_noe_id">The fndsion_noe_id to use as search criteria</param>
		/// <returns>A count of the rows added to the DataSet</returns>
		public int FillByfndsion_noe_id(DataSet dataSetFill, Int32 fndsion_noe_id)
		{
			IDbCommand FillCommand = DataObjectFactory.CreateCommand(DbConnection, CommandType.StoredProcedure);

			FillCommand.CommandText = SelectByfndsion_noe_idCommandName;

			FillCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@fndsion_noe_id", SqlDbType.Int, fndsion_noe_id));
			
			return LoadFromCommand(dataSetFill, FillCommand);
		}	


		/// <summary>
		/// Fill the DataSet with rows from the sazeh table that match the specified sgf_noe_id
		/// </summary>
		/// <param name="dataSetFill">The DataSet to fill</param>
		/// <param name="sgf_noe_id">The sgf_noe_id to use as search criteria</param>
		/// <returns>A count of the rows added to the DataSet</returns>
		public int FillBysgf_noe_id(DataSet dataSetFill, Int32 sgf_noe_id)
		{
			IDbCommand FillCommand = DataObjectFactory.CreateCommand(DbConnection, CommandType.StoredProcedure);

			FillCommand.CommandText = SelectBysgf_noe_idCommandName;

			FillCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@sgf_noe_id", SqlDbType.Int, sgf_noe_id));
			
			return LoadFromCommand(dataSetFill, FillCommand);
		}	


		/// <summary>
		/// Fill the DataSet with rows from the sazeh table that match the specified sklt_noe_id
		/// </summary>
		/// <param name="dataSetFill">The DataSet to fill</param>
		/// <param name="sklt_noe_id">The sklt_noe_id to use as search criteria</param>
		/// <returns>A count of the rows added to the DataSet</returns>
		public int FillBysklt_noe_id(DataSet dataSetFill, Int32 sklt_noe_id)
		{
			IDbCommand FillCommand = DataObjectFactory.CreateCommand(DbConnection, CommandType.StoredProcedure);

			FillCommand.CommandText = SelectBysklt_noe_idCommandName;

			FillCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@sklt_noe_id", SqlDbType.Int, sklt_noe_id));
			
			return LoadFromCommand(dataSetFill, FillCommand);
		}	


		/// <summary>
		/// Fill the DataSet with rows from the sazeh table that match the specified divar_karji_glb_id
		/// </summary>
		/// <param name="dataSetFill">The DataSet to fill</param>
		/// <param name="divar_karji_glb_id">The divar_karji_glb_id to use as search criteria</param>
		/// <returns>A count of the rows added to the DataSet</returns>
		public int FillBydivar_karji_glb_id(DataSet dataSetFill, Int32 divar_karji_glb_id)
		{
			IDbCommand FillCommand = DataObjectFactory.CreateCommand(DbConnection, CommandType.StoredProcedure);

			FillCommand.CommandText = SelectBydivar_karji_glb_idCommandName;

			FillCommand.Parameters.Add(DataObjectFactory.CreateCommandParameter("@divar_karji_glb_id", SqlDbType.Int, divar_karji_glb_id));
			
			return LoadFromCommand(dataSetFill, FillCommand);
		}	


		
		#endregion
	}
}
