/*
** 040_StoredProcedures_Update.sql
**
** Create the stored procedures used 
** when updating existing rows in the database
**
** This script was automatically generated by
** Rad Software NextGeneration
**
** http://www.radsoftware.com.au/
**
*/

/*
** Connect to the AmlakMaskan database
*/
USE [AmlakMaskan]
GO

	
/*
** Create gp_divar_dakli_glb_Update
*/
IF NOT EXISTS (SELECT name FROM sysobjects WHERE id = object_id('gp_divar_dakli_glb_Update'))
BEGIN
	EXEC sp_ExecuteSQL N'CREATE PROCEDURE gp_divar_dakli_glb_Update AS PRINT ''ALTER PROC will update this'''	
END	
GO

/*
** Create gp_memari_Update
*/
IF NOT EXISTS (SELECT name FROM sysobjects WHERE id = object_id('gp_memari_Update'))
BEGIN
	EXEC sp_ExecuteSQL N'CREATE PROCEDURE gp_memari_Update AS PRINT ''ALTER PROC will update this'''	
END	
GO

/*
** Create gp_noe_Update
*/
IF NOT EXISTS (SELECT name FROM sysobjects WHERE id = object_id('gp_noe_Update'))
BEGIN
	EXEC sp_ExecuteSQL N'CREATE PROCEDURE gp_noe_Update AS PRINT ''ALTER PROC will update this'''	
END	
GO

/*
** Create gp_sazeh_Update
*/
IF NOT EXISTS (SELECT name FROM sysobjects WHERE id = object_id('gp_sazeh_Update'))
BEGIN
	EXEC sp_ExecuteSQL N'CREATE PROCEDURE gp_sazeh_Update AS PRINT ''ALTER PROC will update this'''	
END	
GO

/*
**
** Create the stored procedures used 
** when updating existing rows in the database
**
**
*/

/*
** gp_divar_dakli_glb_Update
*/
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
ALTER PROCEDURE gp_divar_dakli_glb_Update
(
	@szh_idOriginal int, 
	@szh_id int,
	@divar_dakli_glb_idOriginal int, 
	@divar_dakli_glb_id int
)
AS
/*
** Update a row in the divar_dakli_glb table using the primary key
*/

UPDATE 
	[divar_dakli_glb]
SET 
	[szh_id] = @szh_id
	,[divar_dakli_glb_id] = @divar_dakli_glb_id
WHERE
	[szh_id] = @szh_idOriginal
	AND [divar_dakli_glb_id] = @divar_dakli_glb_idOriginal


/*
** Select the updated row
*/
SELECT
	gv_divar_dakli_glb.*
FROM
	gv_divar_dakli_glb
WHERE
	[szh_id] = @szh_id
	AND [divar_dakli_glb_id] = @divar_dakli_glb_id


GO
PRINT 'gp_divar_dakli_glb_Update updated'
GO


GRANT EXECUTE ON [gp_divar_dakli_glb_Update] TO public
GO

/*
** gp_memari_Update
*/
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
ALTER PROCEDURE gp_memari_Update
(
	@MemariIDOriginal int, 
	@MemariID int,
	@ReshtehID int,
	@ModiriatID int,
	@ShahrestanID int
)
AS
/*
** Update a row in the memari table using the primary key
*/

UPDATE 
	[memari]
SET 
	[ReshtehID] = @ReshtehID
	,[ModiriatID] = @ModiriatID
	,[ShahrestanID] = @ShahrestanID
WHERE
	[MemariID] = @MemariIDOriginal


/*
** Select the updated row
*/
SELECT
	gv_memari.*
FROM
	gv_memari
WHERE
	[MemariID] = @MemariID


GO
PRINT 'gp_memari_Update updated'
GO


GRANT EXECUTE ON [gp_memari_Update] TO public
GO

/*
** gp_noe_Update
*/
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
ALTER PROCEDURE gp_noe_Update
(
	@noe_idOriginal int, 
	@noe_id int,
	@noe_nam nvarchar(200),
	@noe_cls nvarchar(50),
	@noe_tozi nvarchar(200)
)
AS
/*
** Update a row in the noe table using the primary key
*/

UPDATE 
	[noe]
SET 
	[noe_id] = @noe_id
	,[noe_nam] = @noe_nam
	,[noe_cls] = @noe_cls
	,[noe_tozi] = @noe_tozi
WHERE
	[noe_id] = @noe_idOriginal


/*
** Select the updated row
*/
SELECT
	gv_noe.*
FROM
	gv_noe
WHERE
	[noe_id] = @noe_id


GO
PRINT 'gp_noe_Update updated'
GO


GRANT EXECUTE ON [gp_noe_Update] TO public
GO

/*
** gp_sazeh_Update
*/
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
ALTER PROCEDURE gp_sazeh_Update
(
	@szh_idOriginal int, 
	@szh_id int,
	@mlk_id int,
	@rsht_id int,
	@modirt_id int,
	@shrstan_id int,
	@shobh_id nchar(10),
	@fndsion_noe_id int,
	@fndsion_tozi varchar(max),
	@sgf_noe_id int,
	@sgf_sayr varchar(200),
	@sgf_tozi varchar(max),
	@sklt_noe_id int,
	@sklt_tozi varchar(200),
	@sklt_sayr varchar(max),
	@divar_karji_glb_id int,
	@divar_dakli_glb_partition bit,
	@divar_dakli_glb_simani bit,
	@divar_dakli_glb_lika bit,
	@divar_dakli_glb_hblx bit,
	@divar_dakli_glb_sofali bit,
	@divar_dakli_glb_poma bit,
	@divar_dakli_glb_ajor bit,
	@divar_dakli_glb_drywall bit,
	@divar_dakli_glb_sayer bit,
	@divar_dakli_glb_sayer_val nvarchar(200),
	@divar_dakli_glb_tozi int,
	@thvil_tarikh char(10),
	@thvil_krshnas int
)
AS
/*
** Update a row in the sazeh table using the primary key
*/

UPDATE 
	[sazeh]
SET 
	[mlk_id] = @mlk_id
	,[rsht_id] = @rsht_id
	,[modirt_id] = @modirt_id
	,[shrstan_id] = @shrstan_id
	,[shobh_id] = @shobh_id
	,[fndsion_noe_id] = @fndsion_noe_id
	,[fndsion_tozi] = @fndsion_tozi
	,[sgf_noe_id] = @sgf_noe_id
	,[sgf_sayr] = @sgf_sayr
	,[sgf_tozi] = @sgf_tozi
	,[sklt_noe_id] = @sklt_noe_id
	,[sklt_tozi] = @sklt_tozi
	,[sklt_sayr] = @sklt_sayr
	,[divar_karji_glb_id] = @divar_karji_glb_id
	,[divar_dakli_glb_partition] = @divar_dakli_glb_partition
	,[divar_dakli_glb_simani] = @divar_dakli_glb_simani
	,[divar_dakli_glb_lika] = @divar_dakli_glb_lika
	,[divar_dakli_glb_hblx] = @divar_dakli_glb_hblx
	,[divar_dakli_glb_sofali] = @divar_dakli_glb_sofali
	,[divar_dakli_glb_poma] = @divar_dakli_glb_poma
	,[divar_dakli_glb_ajor] = @divar_dakli_glb_ajor
	,[divar_dakli_glb_drywall] = @divar_dakli_glb_drywall
	,[divar_dakli_glb_sayer] = @divar_dakli_glb_sayer
	,[divar_dakli_glb_sayer_val] = @divar_dakli_glb_sayer_val
	,[divar_dakli_glb_tozi] = @divar_dakli_glb_tozi
	,[thvil_tarikh] = @thvil_tarikh
	,[thvil_krshnas] = @thvil_krshnas
WHERE
	[szh_id] = @szh_idOriginal


/*
** Select the updated row
*/
SELECT
	gv_sazeh.*
FROM
	gv_sazeh
WHERE
	[szh_id] = @szh_id


GO
PRINT 'gp_sazeh_Update updated'
GO


GRANT EXECUTE ON [gp_sazeh_Update] TO public
GO
