/*
** 050_StoredProcedures_Delete.sql
**
** Create the stored procedures used 
** when deleting rows from the database
**
** This script was automatically generated by
** Rad Software NextGeneration
**
** http://www.radsoftware.com.au/
**
*/

/*
** Connect to the AmlakMaskan database
*/
USE [AmlakMaskan]
GO

	
/*
** Create gp_divar_dakli_glb_Delete
*/
IF NOT EXISTS (SELECT name FROM sysobjects WHERE id = object_id('gp_divar_dakli_glb_Delete'))
BEGIN
	EXEC sp_ExecuteSQL N'CREATE PROCEDURE gp_divar_dakli_glb_Delete AS PRINT ''ALTER PROC will update this'''
END	
GO
	
/*
** Create gp_memari_Delete
*/
IF NOT EXISTS (SELECT name FROM sysobjects WHERE id = object_id('gp_memari_Delete'))
BEGIN
	EXEC sp_ExecuteSQL N'CREATE PROCEDURE gp_memari_Delete AS PRINT ''ALTER PROC will update this'''
END	
GO
	
/*
** Create gp_noe_Delete
*/
IF NOT EXISTS (SELECT name FROM sysobjects WHERE id = object_id('gp_noe_Delete'))
BEGIN
	EXEC sp_ExecuteSQL N'CREATE PROCEDURE gp_noe_Delete AS PRINT ''ALTER PROC will update this'''
END	
GO
	
/*
** Create gp_sazeh_Delete
*/
IF NOT EXISTS (SELECT name FROM sysobjects WHERE id = object_id('gp_sazeh_Delete'))
BEGIN
	EXEC sp_ExecuteSQL N'CREATE PROCEDURE gp_sazeh_Delete AS PRINT ''ALTER PROC will update this'''
END	
GO
	
/*
**
** Create the stored procedures used 
** when deleting rows from the database
**
**
*/

/*
** gp_divar_dakli_glb_Delete
*/
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
ALTER PROCEDURE gp_divar_dakli_glb_Delete
(
	@szh_id int,
	@divar_dakli_glb_id int
)
AS
/*
** Delete a row from the divar_dakli_glb table
*/

DELETE 
FROM
	[divar_dakli_glb]
WHERE
	[szh_id] = @szh_id
	AND [divar_dakli_glb_id] = @divar_dakli_glb_id

IF @@ROWCOUNT = 0
BEGIN
	RAISERROR ('Delete failed: Zero rows were deleted from the divar_dakli_glb table', 16, 1)
END

GO
PRINT 'gp_divar_dakli_glb_Delete updated'
GO

GRANT EXECUTE ON [gp_divar_dakli_glb_Delete] TO public

GO


/*
** gp_memari_Delete
*/
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
ALTER PROCEDURE gp_memari_Delete
(
	@MemariID int
)
AS
/*
** Delete a row from the memari table
*/

DELETE 
FROM
	[memari]
WHERE
	[MemariID] = @MemariID

IF @@ROWCOUNT = 0
BEGIN
	RAISERROR ('Delete failed: Zero rows were deleted from the memari table', 16, 1)
END

GO
PRINT 'gp_memari_Delete updated'
GO

GRANT EXECUTE ON [gp_memari_Delete] TO public

GO


/*
** gp_noe_Delete
*/
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
ALTER PROCEDURE gp_noe_Delete
(
	@noe_id int
)
AS
/*
** Delete a row from the noe table
*/

DELETE 
FROM
	[noe]
WHERE
	[noe_id] = @noe_id

IF @@ROWCOUNT = 0
BEGIN
	RAISERROR ('Delete failed: Zero rows were deleted from the noe table', 16, 1)
END

GO
PRINT 'gp_noe_Delete updated'
GO

GRANT EXECUTE ON [gp_noe_Delete] TO public

GO


/*
** gp_sazeh_Delete
*/
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
ALTER PROCEDURE gp_sazeh_Delete
(
	@szh_id int
)
AS
/*
** Delete a row from the sazeh table
*/

DELETE 
FROM
	[sazeh]
WHERE
	[szh_id] = @szh_id

IF @@ROWCOUNT = 0
BEGIN
	RAISERROR ('Delete failed: Zero rows were deleted from the sazeh table', 16, 1)
END

GO
PRINT 'gp_sazeh_Delete updated'
GO

GRANT EXECUTE ON [gp_sazeh_Delete] TO public

GO
