using System;
using System.Data;

using RAD.AppFramework;
using RAD.AppFramework.Data;
using RAD.AppFramework.QueryObjects;

using amlak.Common;
using amlak.Data;
using amlak.DataAccess.Adapters;

namespace amlak.BusinessService.Base
{
	/// <summary>
	/// divar_dakli_glbServiceBase is a base business object implementing the most common data operations 
	/// for the divar_dakli_glb table. 
	/// </summary>
	/// <remarks>
	/// Any application specific business logic must be added to the 
	/// divar_dakli_glbService class. Do not modify this class.
	///
	/// This class was automatically generated by Rad Software NextGeneration <a href="http://www.radsoftware.com.au">http://www.radsoftware.com.au</a>
	/// </remarks>
	public abstract class divar_dakli_glbServiceBase : BusinessServiceObject
	{
		#region Fields
		
		/// <summary>
		/// The strongly-typed DataAdapter to use for Get and Update operations
		/// </summary>
		protected divar_dakli_glbDataAdapter m_divar_dakli_glbAdapter;
				
		#endregion
		
		
		#region Constructors
		
		/// <summary>
		/// Creates a new divar_dakli_glbService
		/// </summary>
		public divar_dakli_glbServiceBase() : base()
		{
			DbConnection = new DatabaseConnection(DataObjectFactory.CreateConnection());
			m_divar_dakli_glbAdapter = new divar_dakli_glbDataAdapter(DbConnection);
		}

		/// <summary>
		/// Creates a new divar_dakli_glbService and sets the Database context
		/// </summary>
		public divar_dakli_glbServiceBase(DatabaseConnection connection) : base()
		{
			UseConnectionAndTransaction(connection);

			m_divar_dakli_glbAdapter = new divar_dakli_glbDataAdapter(connection);
		}
		
		#endregion
		
		
		#region Protected Methods
		
		/// <summary>
		/// Creates an instance of a factory that is used to create Database objects
		/// </summary>
		/// <returns>A DatabaseAccessObjectFactory instance </returns>
		protected override DatabaseAccessObjectFactory CreateDataObjectFactory()
		{
			return CommonFactory.CreateDataObjectFactory();
		}
		
		
		#endregion

		
		#region Public Methods
		
		/// <summary>
		/// Perform any inserts, updates or deletes on the DataSet
		/// </summary>
		/// <param name="dataSetUpdate">The DataSet to update</param>
		/// <returns>The number of rows updated</returns>
		public virtual int UpdateDataSet(divar_dakli_glbDataSet dataSetUpdate)
		{
			m_divar_dakli_glbAdapter.UseConnectionAndTransaction(DbConnection);
		
			return m_divar_dakli_glbAdapter.Update(dataSetUpdate);
		}
		
		
		/// <summary>
		/// Return all rows from the divar_dakli_glb table
		/// </summary>
		/// <param name="dataSetFill">The DataSet to return the rows into</param>
		/// <returns>The number of rows added to the DataSet</returns>
		public virtual int GetAll(divar_dakli_glbDataSet dataSetFill)
		{
			m_divar_dakli_glbAdapter.UseConnectionAndTransaction(DbConnection);
		
			return m_divar_dakli_glbAdapter.Fill(dataSetFill);
		}
		
		
			
		/// <summary>
		/// Return all rows from the divar_dakli_glb table by Primary Key
		/// </summary>
		/// <param name="dataSetFill">The DataSet to return the rows into</param>
		/// <param name="szh_id">The szh_id to use as search criteria</param>
		/// <param name="divar_dakli_glb_id">The divar_dakli_glb_id to use as search criteria</param>
		/// <returns>The number of rows added to the DataSet</returns>
		public virtual int GetByszh_idAnddivar_dakli_glb_id(divar_dakli_glbDataSet dataSetFill, Int32 szh_id, Int32 divar_dakli_glb_id)
		{
			m_divar_dakli_glbAdapter.UseConnectionAndTransaction(DbConnection);
		
			return m_divar_dakli_glbAdapter.FillByszh_idAnddivar_dakli_glb_id(dataSetFill, szh_id, divar_dakli_glb_id);
		}
		
		/// <summary>
		/// Return all rows from the divar_dakli_glb table by divar_dakli_glb_id
		/// </summary>
		/// <param name="dataSetFill">The DataSet to return the rows into</param>
		/// <param name="divar_dakli_glb_id">The divar_dakli_glb_id to use as search criteria</param>
		/// <returns>The number of rows added to the DataSet</returns>
		public virtual int GetBydivar_dakli_glb_id(divar_dakli_glbDataSet dataSetFill, Int32 divar_dakli_glb_id)
		{
			m_divar_dakli_glbAdapter.UseConnectionAndTransaction(DbConnection);
		
			return m_divar_dakli_glbAdapter.FillBydivar_dakli_glb_id(dataSetFill, divar_dakli_glb_id);
		}
	
		
		/// <summary>
		/// Return rows by Query Definition
		/// </summary>
		/// <param name="dataSetFill">The DataSet to return the rows into</param>
		/// <param name="queryDefinition">A Query object that defines the query</param>
		/// <returns>A count of the rows added to the DataSet</returns>
		public virtual int GetByQuery(DataSet dataSetFill, Query queryDefinition)
		{
			m_divar_dakli_glbAdapter.UseConnectionAndTransaction(DbConnection);
		
			return m_divar_dakli_glbAdapter.FillByQuery(dataSetFill, queryDefinition);
		}
		
		
		#endregion
	}
}
