using System;
using System.Data;

using RAD.AppFramework;
using RAD.AppFramework.Data;
using RAD.AppFramework.QueryObjects;

using amlak.Common;
using amlak.Data;
using amlak.DataAccess.Adapters;

namespace amlak.BusinessService.Base
{
	/// <summary>
	/// noeServiceBase is a base business object implementing the most common data operations 
	/// for the noe table. 
	/// </summary>
	/// <remarks>
	/// Any application specific business logic must be added to the 
	/// noeService class. Do not modify this class.
	///
	/// This class was automatically generated by Rad Software NextGeneration <a href="http://www.radsoftware.com.au">http://www.radsoftware.com.au</a>
	/// </remarks>
	public abstract class noeServiceBase : BusinessServiceObject
	{
		#region Fields
		
		/// <summary>
		/// The strongly-typed DataAdapter to use for Get and Update operations
		/// </summary>
		protected noeDataAdapter m_noeAdapter;
				
		#endregion
		
		
		#region Constructors
		
		/// <summary>
		/// Creates a new noeService
		/// </summary>
		public noeServiceBase() : base()
		{
			DbConnection = new DatabaseConnection(DataObjectFactory.CreateConnection());
			m_noeAdapter = new noeDataAdapter(DbConnection);
		}

		/// <summary>
		/// Creates a new noeService and sets the Database context
		/// </summary>
		public noeServiceBase(DatabaseConnection connection) : base()
		{
			UseConnectionAndTransaction(connection);

			m_noeAdapter = new noeDataAdapter(connection);
		}
		
		#endregion
		
		
		#region Protected Methods
		
		/// <summary>
		/// Creates an instance of a factory that is used to create Database objects
		/// </summary>
		/// <returns>A DatabaseAccessObjectFactory instance </returns>
		protected override DatabaseAccessObjectFactory CreateDataObjectFactory()
		{
			return CommonFactory.CreateDataObjectFactory();
		}
		
		
		#endregion

		
		#region Public Methods
		
		/// <summary>
		/// Perform any inserts, updates or deletes on the DataSet
		/// </summary>
		/// <param name="dataSetUpdate">The DataSet to update</param>
		/// <returns>The number of rows updated</returns>
		public virtual int UpdateDataSet(noeDataSet dataSetUpdate)
		{
			m_noeAdapter.UseConnectionAndTransaction(DbConnection);
		
			return m_noeAdapter.Update(dataSetUpdate);
		}
		
		
		/// <summary>
		/// Return all rows from the noe table
		/// </summary>
		/// <param name="dataSetFill">The DataSet to return the rows into</param>
		/// <returns>The number of rows added to the DataSet</returns>
		public virtual int GetAll(noeDataSet dataSetFill)
		{
			m_noeAdapter.UseConnectionAndTransaction(DbConnection);
		
			return m_noeAdapter.Fill(dataSetFill);
		}
		
		
			
		/// <summary>
		/// Return all rows from the noe table by Primary Key
		/// </summary>
		/// <param name="dataSetFill">The DataSet to return the rows into</param>
		/// <param name="noe_id">The noe_id to use as search criteria</param>
		/// <returns>The number of rows added to the DataSet</returns>
		public virtual int GetBynoe_id(noeDataSet dataSetFill, Int32 noe_id)
		{
			m_noeAdapter.UseConnectionAndTransaction(DbConnection);
		
			return m_noeAdapter.FillBynoe_id(dataSetFill, noe_id);
		}
	
		
		/// <summary>
		/// Return rows by Query Definition
		/// </summary>
		/// <param name="dataSetFill">The DataSet to return the rows into</param>
		/// <param name="queryDefinition">A Query object that defines the query</param>
		/// <returns>A count of the rows added to the DataSet</returns>
		public virtual int GetByQuery(DataSet dataSetFill, Query queryDefinition)
		{
			m_noeAdapter.UseConnectionAndTransaction(DbConnection);
		
			return m_noeAdapter.FillByQuery(dataSetFill, queryDefinition);
		}
		
		
		#endregion
	}
}
