using System;
using System.Data;

using RAD.AppFramework;
using RAD.AppFramework.Data;
using RAD.AppFramework.QueryObjects;

using amlak.Common;
using amlak.Data;
using amlak.DataAccess.Adapters;

namespace amlak.BusinessService.Base
{
	/// <summary>
	/// sazehServiceBase is a base business object implementing the most common data operations 
	/// for the sazeh table. 
	/// </summary>
	/// <remarks>
	/// Any application specific business logic must be added to the 
	/// sazehService class. Do not modify this class.
	///
	/// This class was automatically generated by Rad Software NextGeneration <a href="http://www.radsoftware.com.au">http://www.radsoftware.com.au</a>
	/// </remarks>
	public abstract class sazehServiceBase : BusinessServiceObject
	{
		#region Fields
		
		/// <summary>
		/// The strongly-typed DataAdapter to use for Get and Update operations
		/// </summary>
		protected sazehDataAdapter m_sazehAdapter;
				
		#endregion
		
		
		#region Constructors
		
		/// <summary>
		/// Creates a new sazehService
		/// </summary>
		public sazehServiceBase() : base()
		{
			DbConnection = new DatabaseConnection(DataObjectFactory.CreateConnection());
			m_sazehAdapter = new sazehDataAdapter(DbConnection);
		}

		/// <summary>
		/// Creates a new sazehService and sets the Database context
		/// </summary>
		public sazehServiceBase(DatabaseConnection connection) : base()
		{
			UseConnectionAndTransaction(connection);

			m_sazehAdapter = new sazehDataAdapter(connection);
		}
		
		#endregion
		
		
		#region Protected Methods
		
		/// <summary>
		/// Creates an instance of a factory that is used to create Database objects
		/// </summary>
		/// <returns>A DatabaseAccessObjectFactory instance </returns>
		protected override DatabaseAccessObjectFactory CreateDataObjectFactory()
		{
			return CommonFactory.CreateDataObjectFactory();
		}
		
		
		#endregion

		
		#region Public Methods
		
		/// <summary>
		/// Perform any inserts, updates or deletes on the DataSet
		/// </summary>
		/// <param name="dataSetUpdate">The DataSet to update</param>
		/// <returns>The number of rows updated</returns>
		public virtual int UpdateDataSet(sazehDataSet dataSetUpdate)
		{
			m_sazehAdapter.UseConnectionAndTransaction(DbConnection);
		
			return m_sazehAdapter.Update(dataSetUpdate);
		}
		
		
		/// <summary>
		/// Return all rows from the sazeh table
		/// </summary>
		/// <param name="dataSetFill">The DataSet to return the rows into</param>
		/// <returns>The number of rows added to the DataSet</returns>
		public virtual int GetAll(sazehDataSet dataSetFill)
		{
			m_sazehAdapter.UseConnectionAndTransaction(DbConnection);
		
			return m_sazehAdapter.Fill(dataSetFill);
		}
		
		
			
		/// <summary>
		/// Return all rows from the sazeh table by Primary Key
		/// </summary>
		/// <param name="dataSetFill">The DataSet to return the rows into</param>
		/// <param name="szh_id">The szh_id to use as search criteria</param>
		/// <returns>The number of rows added to the DataSet</returns>
		public virtual int GetByszh_id(sazehDataSet dataSetFill, Int32 szh_id)
		{
			m_sazehAdapter.UseConnectionAndTransaction(DbConnection);
		
			return m_sazehAdapter.FillByszh_id(dataSetFill, szh_id);
		}
		
		/// <summary>
		/// Return all rows from the sazeh table by fndsion_noe_id
		/// </summary>
		/// <param name="dataSetFill">The DataSet to return the rows into</param>
		/// <param name="fndsion_noe_id">The fndsion_noe_id to use as search criteria</param>
		/// <returns>The number of rows added to the DataSet</returns>
		public virtual int GetByfndsion_noe_id(sazehDataSet dataSetFill, Int32 fndsion_noe_id)
		{
			m_sazehAdapter.UseConnectionAndTransaction(DbConnection);
		
			return m_sazehAdapter.FillByfndsion_noe_id(dataSetFill, fndsion_noe_id);
		}
		
		/// <summary>
		/// Return all rows from the sazeh table by sgf_noe_id
		/// </summary>
		/// <param name="dataSetFill">The DataSet to return the rows into</param>
		/// <param name="sgf_noe_id">The sgf_noe_id to use as search criteria</param>
		/// <returns>The number of rows added to the DataSet</returns>
		public virtual int GetBysgf_noe_id(sazehDataSet dataSetFill, Int32 sgf_noe_id)
		{
			m_sazehAdapter.UseConnectionAndTransaction(DbConnection);
		
			return m_sazehAdapter.FillBysgf_noe_id(dataSetFill, sgf_noe_id);
		}
		
		/// <summary>
		/// Return all rows from the sazeh table by sklt_noe_id
		/// </summary>
		/// <param name="dataSetFill">The DataSet to return the rows into</param>
		/// <param name="sklt_noe_id">The sklt_noe_id to use as search criteria</param>
		/// <returns>The number of rows added to the DataSet</returns>
		public virtual int GetBysklt_noe_id(sazehDataSet dataSetFill, Int32 sklt_noe_id)
		{
			m_sazehAdapter.UseConnectionAndTransaction(DbConnection);
		
			return m_sazehAdapter.FillBysklt_noe_id(dataSetFill, sklt_noe_id);
		}
		
		/// <summary>
		/// Return all rows from the sazeh table by divar_karji_glb_id
		/// </summary>
		/// <param name="dataSetFill">The DataSet to return the rows into</param>
		/// <param name="divar_karji_glb_id">The divar_karji_glb_id to use as search criteria</param>
		/// <returns>The number of rows added to the DataSet</returns>
		public virtual int GetBydivar_karji_glb_id(sazehDataSet dataSetFill, Int32 divar_karji_glb_id)
		{
			m_sazehAdapter.UseConnectionAndTransaction(DbConnection);
		
			return m_sazehAdapter.FillBydivar_karji_glb_id(dataSetFill, divar_karji_glb_id);
		}
	
		
		/// <summary>
		/// Return rows by Query Definition
		/// </summary>
		/// <param name="dataSetFill">The DataSet to return the rows into</param>
		/// <param name="queryDefinition">A Query object that defines the query</param>
		/// <returns>A count of the rows added to the DataSet</returns>
		public virtual int GetByQuery(DataSet dataSetFill, Query queryDefinition)
		{
			m_sazehAdapter.UseConnectionAndTransaction(DbConnection);
		
			return m_sazehAdapter.FillByQuery(dataSetFill, queryDefinition);
		}
		
		
		#endregion
	}
}
