@ECHO OFF

REM // _RegenerateStronglyTypedDataSets.bat
REM //
REM // This batch file calls the .NET Framework utility xsd.exe to regenerate
REM // strongly typed dataset classes from the schema definitions stored
REM // in the .xsd files.
REM //
REM // This file was auto-generated by Rad Software NextGeneration 
REM // http://www.radsoftware.com.au

SET XSDTOOL="Bin\XSD.EXE"

IF NOT EXIST TempXsdOutput MD TempXsdOutput
	
ECHO Generating divar_dakli_glbDataSet ...
SET ContinuePrompt=
%XSDTOOL%         /dataset /language:CS /namespace:amlak.Data /out:TempXsdOutput divar_dakli_glbDataSet.xsd
ECHO.
IF ERRORLEVEL 1 SET /p ContinuePrompt="Do you want to continue generating the other DataSet classes (y/n)? "
IF "%ContinuePrompt%"=="n" EXIT /B
MOVE /Y TempXsdOutput\divar_dakli_glbDataSet.cs divar_dakli_glbDataSet.Designer.cs

	
ECHO Generating memariDataSet ...
SET ContinuePrompt=
%XSDTOOL% /nologo /dataset /language:CS /namespace:amlak.Data /out:TempXsdOutput memariDataSet.xsd > nul
ECHO.
IF ERRORLEVEL 1 SET /p ContinuePrompt="Do you want to continue generating the other DataSet classes (y/n)? "
IF "%ContinuePrompt%"=="n" EXIT /B
MOVE /Y TempXsdOutput\memariDataSet.cs memariDataSet.Designer.cs

	
ECHO Generating noeDataSet ...
SET ContinuePrompt=
%XSDTOOL% /nologo /dataset /language:CS /namespace:amlak.Data /out:TempXsdOutput noeDataSet.xsd > nul
ECHO.
IF ERRORLEVEL 1 SET /p ContinuePrompt="Do you want to continue generating the other DataSet classes (y/n)? "
IF "%ContinuePrompt%"=="n" EXIT /B
MOVE /Y TempXsdOutput\noeDataSet.cs noeDataSet.Designer.cs

	
ECHO Generating sazehDataSet ...
SET ContinuePrompt=
%XSDTOOL% /nologo /dataset /language:CS /namespace:amlak.Data /out:TempXsdOutput sazehDataSet.xsd > nul
ECHO.
IF ERRORLEVEL 1 SET /p ContinuePrompt="Do you want to continue generating the other DataSet classes (y/n)? "
IF "%ContinuePrompt%"=="n" EXIT /B
MOVE /Y TempXsdOutput\sazehDataSet.cs sazehDataSet.Designer.cs

IF EXIST TempXsdOutput RMDIR TempXsdOutput


SET ContinuePrompt=

ECHO DataSet Class generation complete
Pause
