//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace amlak.Data {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("sazehDataSet")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class sazehDataSet : global::System.Data.DataSet {
        
        private sazehDataTable tablesazeh;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public sazehDataSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected sazehDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["sazeh"] != null)) {
                    base.Tables.Add(new sazehDataTable(ds.Tables["sazeh"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public sazehDataTable sazeh {
            get {
                return this.tablesazeh;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            sazehDataSet cln = ((sazehDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["sazeh"] != null)) {
                    base.Tables.Add(new sazehDataTable(ds.Tables["sazeh"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tablesazeh = ((sazehDataTable)(base.Tables["sazeh"]));
            if ((initTable == true)) {
                if ((this.tablesazeh != null)) {
                    this.tablesazeh.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "sazehDataSet";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/sazehDataSet.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tablesazeh = new sazehDataTable();
            base.Tables.Add(this.tablesazeh);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializesazeh() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            sazehDataSet ds = new sazehDataSet();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void sazehRowChangeEventHandler(object sender, sazehRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class sazehDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnszh_id;
            
            private global::System.Data.DataColumn columnmlk_id;
            
            private global::System.Data.DataColumn columnrsht_id;
            
            private global::System.Data.DataColumn columnmodirt_id;
            
            private global::System.Data.DataColumn columnshrstan_id;
            
            private global::System.Data.DataColumn columnshobh_id;
            
            private global::System.Data.DataColumn columnfndsion_noe_id;
            
            private global::System.Data.DataColumn columnfndsion_tozi;
            
            private global::System.Data.DataColumn columnsgf_noe_id;
            
            private global::System.Data.DataColumn columnsgf_sayr;
            
            private global::System.Data.DataColumn columnsgf_tozi;
            
            private global::System.Data.DataColumn columnsklt_noe_id;
            
            private global::System.Data.DataColumn columnsklt_tozi;
            
            private global::System.Data.DataColumn columnsklt_sayr;
            
            private global::System.Data.DataColumn columndivar_karji_glb_id;
            
            private global::System.Data.DataColumn columndivar_dakli_glb_partition;
            
            private global::System.Data.DataColumn columndivar_dakli_glb_simani;
            
            private global::System.Data.DataColumn columndivar_dakli_glb_lika;
            
            private global::System.Data.DataColumn columndivar_dakli_glb_hblx;
            
            private global::System.Data.DataColumn columndivar_dakli_glb_sofali;
            
            private global::System.Data.DataColumn columndivar_dakli_glb_poma;
            
            private global::System.Data.DataColumn columndivar_dakli_glb_ajor;
            
            private global::System.Data.DataColumn columndivar_dakli_glb_drywall;
            
            private global::System.Data.DataColumn columndivar_dakli_glb_sayer;
            
            private global::System.Data.DataColumn columndivar_dakli_glb_sayer_val;
            
            private global::System.Data.DataColumn columndivar_dakli_glb_tozi;
            
            private global::System.Data.DataColumn columnthvil_tarikh;
            
            private global::System.Data.DataColumn columnthvil_krshnas;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public sazehDataTable() {
                this.TableName = "sazeh";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal sazehDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected sazehDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn szh_idColumn {
                get {
                    return this.columnszh_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn mlk_idColumn {
                get {
                    return this.columnmlk_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn rsht_idColumn {
                get {
                    return this.columnrsht_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn modirt_idColumn {
                get {
                    return this.columnmodirt_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn shrstan_idColumn {
                get {
                    return this.columnshrstan_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn shobh_idColumn {
                get {
                    return this.columnshobh_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fndsion_noe_idColumn {
                get {
                    return this.columnfndsion_noe_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fndsion_toziColumn {
                get {
                    return this.columnfndsion_tozi;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn sgf_noe_idColumn {
                get {
                    return this.columnsgf_noe_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn sgf_sayrColumn {
                get {
                    return this.columnsgf_sayr;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn sgf_toziColumn {
                get {
                    return this.columnsgf_tozi;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn sklt_noe_idColumn {
                get {
                    return this.columnsklt_noe_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn sklt_toziColumn {
                get {
                    return this.columnsklt_tozi;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn sklt_sayrColumn {
                get {
                    return this.columnsklt_sayr;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn divar_karji_glb_idColumn {
                get {
                    return this.columndivar_karji_glb_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn divar_dakli_glb_partitionColumn {
                get {
                    return this.columndivar_dakli_glb_partition;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn divar_dakli_glb_simaniColumn {
                get {
                    return this.columndivar_dakli_glb_simani;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn divar_dakli_glb_likaColumn {
                get {
                    return this.columndivar_dakli_glb_lika;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn divar_dakli_glb_hblxColumn {
                get {
                    return this.columndivar_dakli_glb_hblx;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn divar_dakli_glb_sofaliColumn {
                get {
                    return this.columndivar_dakli_glb_sofali;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn divar_dakli_glb_pomaColumn {
                get {
                    return this.columndivar_dakli_glb_poma;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn divar_dakli_glb_ajorColumn {
                get {
                    return this.columndivar_dakli_glb_ajor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn divar_dakli_glb_drywallColumn {
                get {
                    return this.columndivar_dakli_glb_drywall;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn divar_dakli_glb_sayerColumn {
                get {
                    return this.columndivar_dakli_glb_sayer;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn divar_dakli_glb_sayer_valColumn {
                get {
                    return this.columndivar_dakli_glb_sayer_val;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn divar_dakli_glb_toziColumn {
                get {
                    return this.columndivar_dakli_glb_tozi;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn thvil_tarikhColumn {
                get {
                    return this.columnthvil_tarikh;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn thvil_krshnasColumn {
                get {
                    return this.columnthvil_krshnas;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public sazehRow this[int index] {
                get {
                    return ((sazehRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event sazehRowChangeEventHandler sazehRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event sazehRowChangeEventHandler sazehRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event sazehRowChangeEventHandler sazehRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event sazehRowChangeEventHandler sazehRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddsazehRow(sazehRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public sazehRow AddsazehRow(
                        int mlk_id, 
                        int rsht_id, 
                        int modirt_id, 
                        int shrstan_id, 
                        string shobh_id, 
                        int fndsion_noe_id, 
                        string fndsion_tozi, 
                        int sgf_noe_id, 
                        string sgf_sayr, 
                        string sgf_tozi, 
                        int sklt_noe_id, 
                        string sklt_tozi, 
                        string sklt_sayr, 
                        int divar_karji_glb_id, 
                        bool divar_dakli_glb_partition, 
                        bool divar_dakli_glb_simani, 
                        bool divar_dakli_glb_lika, 
                        bool divar_dakli_glb_hblx, 
                        bool divar_dakli_glb_sofali, 
                        bool divar_dakli_glb_poma, 
                        bool divar_dakli_glb_ajor, 
                        bool divar_dakli_glb_drywall, 
                        bool divar_dakli_glb_sayer, 
                        string divar_dakli_glb_sayer_val, 
                        int divar_dakli_glb_tozi, 
                        string thvil_tarikh, 
                        int thvil_krshnas) {
                sazehRow rowsazehRow = ((sazehRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        null,
                        mlk_id,
                        rsht_id,
                        modirt_id,
                        shrstan_id,
                        shobh_id,
                        fndsion_noe_id,
                        fndsion_tozi,
                        sgf_noe_id,
                        sgf_sayr,
                        sgf_tozi,
                        sklt_noe_id,
                        sklt_tozi,
                        sklt_sayr,
                        divar_karji_glb_id,
                        divar_dakli_glb_partition,
                        divar_dakli_glb_simani,
                        divar_dakli_glb_lika,
                        divar_dakli_glb_hblx,
                        divar_dakli_glb_sofali,
                        divar_dakli_glb_poma,
                        divar_dakli_glb_ajor,
                        divar_dakli_glb_drywall,
                        divar_dakli_glb_sayer,
                        divar_dakli_glb_sayer_val,
                        divar_dakli_glb_tozi,
                        thvil_tarikh,
                        thvil_krshnas};
                rowsazehRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowsazehRow);
                return rowsazehRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public sazehRow FindByszh_id(int szh_id) {
                return ((sazehRow)(this.Rows.Find(new object[] {
                            szh_id})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                sazehDataTable cln = ((sazehDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new sazehDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnszh_id = base.Columns["szh_id"];
                this.columnmlk_id = base.Columns["mlk_id"];
                this.columnrsht_id = base.Columns["rsht_id"];
                this.columnmodirt_id = base.Columns["modirt_id"];
                this.columnshrstan_id = base.Columns["shrstan_id"];
                this.columnshobh_id = base.Columns["shobh_id"];
                this.columnfndsion_noe_id = base.Columns["fndsion_noe_id"];
                this.columnfndsion_tozi = base.Columns["fndsion_tozi"];
                this.columnsgf_noe_id = base.Columns["sgf_noe_id"];
                this.columnsgf_sayr = base.Columns["sgf_sayr"];
                this.columnsgf_tozi = base.Columns["sgf_tozi"];
                this.columnsklt_noe_id = base.Columns["sklt_noe_id"];
                this.columnsklt_tozi = base.Columns["sklt_tozi"];
                this.columnsklt_sayr = base.Columns["sklt_sayr"];
                this.columndivar_karji_glb_id = base.Columns["divar_karji_glb_id"];
                this.columndivar_dakli_glb_partition = base.Columns["divar_dakli_glb_partition"];
                this.columndivar_dakli_glb_simani = base.Columns["divar_dakli_glb_simani"];
                this.columndivar_dakli_glb_lika = base.Columns["divar_dakli_glb_lika"];
                this.columndivar_dakli_glb_hblx = base.Columns["divar_dakli_glb_hblx"];
                this.columndivar_dakli_glb_sofali = base.Columns["divar_dakli_glb_sofali"];
                this.columndivar_dakli_glb_poma = base.Columns["divar_dakli_glb_poma"];
                this.columndivar_dakli_glb_ajor = base.Columns["divar_dakli_glb_ajor"];
                this.columndivar_dakli_glb_drywall = base.Columns["divar_dakli_glb_drywall"];
                this.columndivar_dakli_glb_sayer = base.Columns["divar_dakli_glb_sayer"];
                this.columndivar_dakli_glb_sayer_val = base.Columns["divar_dakli_glb_sayer_val"];
                this.columndivar_dakli_glb_tozi = base.Columns["divar_dakli_glb_tozi"];
                this.columnthvil_tarikh = base.Columns["thvil_tarikh"];
                this.columnthvil_krshnas = base.Columns["thvil_krshnas"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnszh_id = new global::System.Data.DataColumn("szh_id", typeof(int), null, global::System.Data.MappingType.Element);
                this.columnszh_id.ExtendedProperties.Add("typedName", "szh_id");
                base.Columns.Add(this.columnszh_id);
                this.columnmlk_id = new global::System.Data.DataColumn("mlk_id", typeof(int), null, global::System.Data.MappingType.Element);
                this.columnmlk_id.ExtendedProperties.Add("typedName", "mlk_id");
                base.Columns.Add(this.columnmlk_id);
                this.columnrsht_id = new global::System.Data.DataColumn("rsht_id", typeof(int), null, global::System.Data.MappingType.Element);
                this.columnrsht_id.ExtendedProperties.Add("typedName", "rsht_id");
                base.Columns.Add(this.columnrsht_id);
                this.columnmodirt_id = new global::System.Data.DataColumn("modirt_id", typeof(int), null, global::System.Data.MappingType.Element);
                this.columnmodirt_id.ExtendedProperties.Add("typedName", "modirt_id");
                base.Columns.Add(this.columnmodirt_id);
                this.columnshrstan_id = new global::System.Data.DataColumn("shrstan_id", typeof(int), null, global::System.Data.MappingType.Element);
                this.columnshrstan_id.ExtendedProperties.Add("typedName", "shrstan_id");
                base.Columns.Add(this.columnshrstan_id);
                this.columnshobh_id = new global::System.Data.DataColumn("shobh_id", typeof(string), null, global::System.Data.MappingType.Element);
                this.columnshobh_id.ExtendedProperties.Add("typedName", "shobh_id");
                base.Columns.Add(this.columnshobh_id);
                this.columnfndsion_noe_id = new global::System.Data.DataColumn("fndsion_noe_id", typeof(int), null, global::System.Data.MappingType.Element);
                this.columnfndsion_noe_id.ExtendedProperties.Add("typedName", "fndsion_noe_id");
                base.Columns.Add(this.columnfndsion_noe_id);
                this.columnfndsion_tozi = new global::System.Data.DataColumn("fndsion_tozi", typeof(string), null, global::System.Data.MappingType.Element);
                this.columnfndsion_tozi.ExtendedProperties.Add("typedName", "fndsion_tozi");
                base.Columns.Add(this.columnfndsion_tozi);
                this.columnsgf_noe_id = new global::System.Data.DataColumn("sgf_noe_id", typeof(int), null, global::System.Data.MappingType.Element);
                this.columnsgf_noe_id.ExtendedProperties.Add("typedName", "sgf_noe_id");
                base.Columns.Add(this.columnsgf_noe_id);
                this.columnsgf_sayr = new global::System.Data.DataColumn("sgf_sayr", typeof(string), null, global::System.Data.MappingType.Element);
                this.columnsgf_sayr.ExtendedProperties.Add("typedName", "sgf_sayr");
                base.Columns.Add(this.columnsgf_sayr);
                this.columnsgf_tozi = new global::System.Data.DataColumn("sgf_tozi", typeof(string), null, global::System.Data.MappingType.Element);
                this.columnsgf_tozi.ExtendedProperties.Add("typedName", "sgf_tozi");
                base.Columns.Add(this.columnsgf_tozi);
                this.columnsklt_noe_id = new global::System.Data.DataColumn("sklt_noe_id", typeof(int), null, global::System.Data.MappingType.Element);
                this.columnsklt_noe_id.ExtendedProperties.Add("typedName", "sklt_noe_id");
                base.Columns.Add(this.columnsklt_noe_id);
                this.columnsklt_tozi = new global::System.Data.DataColumn("sklt_tozi", typeof(string), null, global::System.Data.MappingType.Element);
                this.columnsklt_tozi.ExtendedProperties.Add("typedName", "sklt_tozi");
                base.Columns.Add(this.columnsklt_tozi);
                this.columnsklt_sayr = new global::System.Data.DataColumn("sklt_sayr", typeof(string), null, global::System.Data.MappingType.Element);
                this.columnsklt_sayr.ExtendedProperties.Add("typedName", "sklt_sayr");
                base.Columns.Add(this.columnsklt_sayr);
                this.columndivar_karji_glb_id = new global::System.Data.DataColumn("divar_karji_glb_id", typeof(int), null, global::System.Data.MappingType.Element);
                this.columndivar_karji_glb_id.ExtendedProperties.Add("typedName", "divar_karji_glb_id");
                base.Columns.Add(this.columndivar_karji_glb_id);
                this.columndivar_dakli_glb_partition = new global::System.Data.DataColumn("divar_dakli_glb_partition", typeof(bool), null, global::System.Data.MappingType.Element);
                this.columndivar_dakli_glb_partition.ExtendedProperties.Add("typedName", "divar_dakli_glb_partition");
                base.Columns.Add(this.columndivar_dakli_glb_partition);
                this.columndivar_dakli_glb_simani = new global::System.Data.DataColumn("divar_dakli_glb_simani", typeof(bool), null, global::System.Data.MappingType.Element);
                this.columndivar_dakli_glb_simani.ExtendedProperties.Add("typedName", "divar_dakli_glb_simani");
                base.Columns.Add(this.columndivar_dakli_glb_simani);
                this.columndivar_dakli_glb_lika = new global::System.Data.DataColumn("divar_dakli_glb_lika", typeof(bool), null, global::System.Data.MappingType.Element);
                this.columndivar_dakli_glb_lika.ExtendedProperties.Add("typedName", "divar_dakli_glb_lika");
                base.Columns.Add(this.columndivar_dakli_glb_lika);
                this.columndivar_dakli_glb_hblx = new global::System.Data.DataColumn("divar_dakli_glb_hblx", typeof(bool), null, global::System.Data.MappingType.Element);
                this.columndivar_dakli_glb_hblx.ExtendedProperties.Add("typedName", "divar_dakli_glb_hblx");
                base.Columns.Add(this.columndivar_dakli_glb_hblx);
                this.columndivar_dakli_glb_sofali = new global::System.Data.DataColumn("divar_dakli_glb_sofali", typeof(bool), null, global::System.Data.MappingType.Element);
                this.columndivar_dakli_glb_sofali.ExtendedProperties.Add("typedName", "divar_dakli_glb_sofali");
                base.Columns.Add(this.columndivar_dakli_glb_sofali);
                this.columndivar_dakli_glb_poma = new global::System.Data.DataColumn("divar_dakli_glb_poma", typeof(bool), null, global::System.Data.MappingType.Element);
                this.columndivar_dakli_glb_poma.ExtendedProperties.Add("typedName", "divar_dakli_glb_poma");
                base.Columns.Add(this.columndivar_dakli_glb_poma);
                this.columndivar_dakli_glb_ajor = new global::System.Data.DataColumn("divar_dakli_glb_ajor", typeof(bool), null, global::System.Data.MappingType.Element);
                this.columndivar_dakli_glb_ajor.ExtendedProperties.Add("typedName", "divar_dakli_glb_ajor");
                base.Columns.Add(this.columndivar_dakli_glb_ajor);
                this.columndivar_dakli_glb_drywall = new global::System.Data.DataColumn("divar_dakli_glb_drywall", typeof(bool), null, global::System.Data.MappingType.Element);
                this.columndivar_dakli_glb_drywall.ExtendedProperties.Add("typedName", "divar_dakli_glb_drywall");
                base.Columns.Add(this.columndivar_dakli_glb_drywall);
                this.columndivar_dakli_glb_sayer = new global::System.Data.DataColumn("divar_dakli_glb_sayer", typeof(bool), null, global::System.Data.MappingType.Element);
                this.columndivar_dakli_glb_sayer.ExtendedProperties.Add("typedName", "divar_dakli_glb_sayer");
                base.Columns.Add(this.columndivar_dakli_glb_sayer);
                this.columndivar_dakli_glb_sayer_val = new global::System.Data.DataColumn("divar_dakli_glb_sayer_val", typeof(string), null, global::System.Data.MappingType.Element);
                this.columndivar_dakli_glb_sayer_val.ExtendedProperties.Add("typedName", "divar_dakli_glb_sayer_val");
                base.Columns.Add(this.columndivar_dakli_glb_sayer_val);
                this.columndivar_dakli_glb_tozi = new global::System.Data.DataColumn("divar_dakli_glb_tozi", typeof(int), null, global::System.Data.MappingType.Element);
                this.columndivar_dakli_glb_tozi.ExtendedProperties.Add("typedName", "divar_dakli_glb_tozi");
                base.Columns.Add(this.columndivar_dakli_glb_tozi);
                this.columnthvil_tarikh = new global::System.Data.DataColumn("thvil_tarikh", typeof(string), null, global::System.Data.MappingType.Element);
                this.columnthvil_tarikh.ExtendedProperties.Add("typedName", "thvil_tarikh");
                base.Columns.Add(this.columnthvil_tarikh);
                this.columnthvil_krshnas = new global::System.Data.DataColumn("thvil_krshnas", typeof(int), null, global::System.Data.MappingType.Element);
                this.columnthvil_krshnas.ExtendedProperties.Add("typedName", "thvil_krshnas");
                base.Columns.Add(this.columnthvil_krshnas);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("sazehDataSetKey1", new global::System.Data.DataColumn[] {
                                this.columnszh_id}, true));
                this.columnszh_id.AutoIncrement = true;
                this.columnszh_id.AutoIncrementSeed = -1;
                this.columnszh_id.AutoIncrementStep = -1;
                this.columnszh_id.AllowDBNull = false;
                this.columnszh_id.ReadOnly = true;
                this.columnszh_id.Unique = true;
                this.columnszh_id.Caption = "Szh Id";
                this.columnmlk_id.Caption = "Mlk Id";
                this.columnrsht_id.AllowDBNull = false;
                this.columnrsht_id.Caption = "Rsht Id";
                this.columnmodirt_id.AllowDBNull = false;
                this.columnmodirt_id.Caption = "Modirt Id";
                this.columnshrstan_id.AllowDBNull = false;
                this.columnshrstan_id.Caption = "Shrstan Id";
                this.columnshobh_id.Caption = "Shobh Id";
                this.columnfndsion_noe_id.AllowDBNull = false;
                this.columnfndsion_noe_id.Caption = "Fndsion Noe Id";
                this.columnfndsion_tozi.Caption = "Fndsion Tozi";
                this.columnsgf_noe_id.AllowDBNull = false;
                this.columnsgf_noe_id.Caption = "Sgf Noe Id";
                this.columnsgf_sayr.Caption = "Sgf Sayr";
                this.columnsgf_tozi.Caption = "Sgf Tozi";
                this.columnsklt_noe_id.AllowDBNull = false;
                this.columnsklt_noe_id.Caption = "Sklt Noe Id";
                this.columnsklt_tozi.Caption = "Sklt Tozi";
                this.columnsklt_sayr.Caption = "Sklt Sayr";
                this.columndivar_karji_glb_id.AllowDBNull = false;
                this.columndivar_karji_glb_id.Caption = "Divar Karji Glb Id";
                this.columndivar_dakli_glb_partition.Caption = "Divar Dakli Glb Partition";
                this.columndivar_dakli_glb_simani.Caption = "Divar Dakli Glb Simani";
                this.columndivar_dakli_glb_lika.Caption = "Divar Dakli Glb Lika";
                this.columndivar_dakli_glb_hblx.Caption = "Divar Dakli Glb Hblx";
                this.columndivar_dakli_glb_sofali.Caption = "Divar Dakli Glb Sofali";
                this.columndivar_dakli_glb_poma.Caption = "Divar Dakli Glb Poma";
                this.columndivar_dakli_glb_ajor.Caption = "Divar Dakli Glb Ajor";
                this.columndivar_dakli_glb_drywall.Caption = "Divar Dakli Glb Drywall";
                this.columndivar_dakli_glb_sayer.Caption = "Divar Dakli Glb Sayer";
                this.columndivar_dakli_glb_sayer_val.Caption = "Divar Dakli Glb Sayer Val";
                this.columndivar_dakli_glb_tozi.Caption = "Divar Dakli Glb Tozi";
                this.columnthvil_tarikh.AllowDBNull = false;
                this.columnthvil_tarikh.Caption = "Thvil Tarikh";
                this.columnthvil_krshnas.AllowDBNull = false;
                this.columnthvil_krshnas.Caption = "Thvil Krshnas";
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public sazehRow NewsazehRow() {
                return ((sazehRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new sazehRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(sazehRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.sazehRowChanged != null)) {
                    this.sazehRowChanged(this, new sazehRowChangeEvent(((sazehRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.sazehRowChanging != null)) {
                    this.sazehRowChanging(this, new sazehRowChangeEvent(((sazehRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.sazehRowDeleted != null)) {
                    this.sazehRowDeleted(this, new sazehRowChangeEvent(((sazehRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.sazehRowDeleting != null)) {
                    this.sazehRowDeleting(this, new sazehRowChangeEvent(((sazehRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemovesazehRow(sazehRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                sazehDataSet ds = new sazehDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "sazehDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class sazehRow : global::System.Data.DataRow {
            
            private sazehDataTable tablesazeh;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal sazehRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablesazeh = ((sazehDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int szh_id {
                get {
                    return ((int)(this[this.tablesazeh.szh_idColumn]));
                }
                set {
                    this[this.tablesazeh.szh_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int mlk_id {
                get {
                    try {
                        return ((int)(this[this.tablesazeh.mlk_idColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'mlk_id\' in table \'sazeh\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesazeh.mlk_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int rsht_id {
                get {
                    return ((int)(this[this.tablesazeh.rsht_idColumn]));
                }
                set {
                    this[this.tablesazeh.rsht_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int modirt_id {
                get {
                    return ((int)(this[this.tablesazeh.modirt_idColumn]));
                }
                set {
                    this[this.tablesazeh.modirt_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int shrstan_id {
                get {
                    return ((int)(this[this.tablesazeh.shrstan_idColumn]));
                }
                set {
                    this[this.tablesazeh.shrstan_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string shobh_id {
                get {
                    try {
                        return ((string)(this[this.tablesazeh.shobh_idColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'shobh_id\' in table \'sazeh\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesazeh.shobh_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int fndsion_noe_id {
                get {
                    return ((int)(this[this.tablesazeh.fndsion_noe_idColumn]));
                }
                set {
                    this[this.tablesazeh.fndsion_noe_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string fndsion_tozi {
                get {
                    try {
                        return ((string)(this[this.tablesazeh.fndsion_toziColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fndsion_tozi\' in table \'sazeh\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesazeh.fndsion_toziColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int sgf_noe_id {
                get {
                    return ((int)(this[this.tablesazeh.sgf_noe_idColumn]));
                }
                set {
                    this[this.tablesazeh.sgf_noe_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string sgf_sayr {
                get {
                    try {
                        return ((string)(this[this.tablesazeh.sgf_sayrColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'sgf_sayr\' in table \'sazeh\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesazeh.sgf_sayrColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string sgf_tozi {
                get {
                    try {
                        return ((string)(this[this.tablesazeh.sgf_toziColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'sgf_tozi\' in table \'sazeh\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesazeh.sgf_toziColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int sklt_noe_id {
                get {
                    return ((int)(this[this.tablesazeh.sklt_noe_idColumn]));
                }
                set {
                    this[this.tablesazeh.sklt_noe_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string sklt_tozi {
                get {
                    try {
                        return ((string)(this[this.tablesazeh.sklt_toziColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'sklt_tozi\' in table \'sazeh\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesazeh.sklt_toziColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string sklt_sayr {
                get {
                    try {
                        return ((string)(this[this.tablesazeh.sklt_sayrColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'sklt_sayr\' in table \'sazeh\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesazeh.sklt_sayrColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int divar_karji_glb_id {
                get {
                    return ((int)(this[this.tablesazeh.divar_karji_glb_idColumn]));
                }
                set {
                    this[this.tablesazeh.divar_karji_glb_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool divar_dakli_glb_partition {
                get {
                    try {
                        return ((bool)(this[this.tablesazeh.divar_dakli_glb_partitionColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'divar_dakli_glb_partition\' in table \'sazeh\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesazeh.divar_dakli_glb_partitionColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool divar_dakli_glb_simani {
                get {
                    try {
                        return ((bool)(this[this.tablesazeh.divar_dakli_glb_simaniColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'divar_dakli_glb_simani\' in table \'sazeh\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesazeh.divar_dakli_glb_simaniColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool divar_dakli_glb_lika {
                get {
                    try {
                        return ((bool)(this[this.tablesazeh.divar_dakli_glb_likaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'divar_dakli_glb_lika\' in table \'sazeh\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesazeh.divar_dakli_glb_likaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool divar_dakli_glb_hblx {
                get {
                    try {
                        return ((bool)(this[this.tablesazeh.divar_dakli_glb_hblxColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'divar_dakli_glb_hblx\' in table \'sazeh\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesazeh.divar_dakli_glb_hblxColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool divar_dakli_glb_sofali {
                get {
                    try {
                        return ((bool)(this[this.tablesazeh.divar_dakli_glb_sofaliColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'divar_dakli_glb_sofali\' in table \'sazeh\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesazeh.divar_dakli_glb_sofaliColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool divar_dakli_glb_poma {
                get {
                    try {
                        return ((bool)(this[this.tablesazeh.divar_dakli_glb_pomaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'divar_dakli_glb_poma\' in table \'sazeh\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesazeh.divar_dakli_glb_pomaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool divar_dakli_glb_ajor {
                get {
                    try {
                        return ((bool)(this[this.tablesazeh.divar_dakli_glb_ajorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'divar_dakli_glb_ajor\' in table \'sazeh\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesazeh.divar_dakli_glb_ajorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool divar_dakli_glb_drywall {
                get {
                    try {
                        return ((bool)(this[this.tablesazeh.divar_dakli_glb_drywallColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'divar_dakli_glb_drywall\' in table \'sazeh\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesazeh.divar_dakli_glb_drywallColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool divar_dakli_glb_sayer {
                get {
                    try {
                        return ((bool)(this[this.tablesazeh.divar_dakli_glb_sayerColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'divar_dakli_glb_sayer\' in table \'sazeh\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesazeh.divar_dakli_glb_sayerColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string divar_dakli_glb_sayer_val {
                get {
                    try {
                        return ((string)(this[this.tablesazeh.divar_dakli_glb_sayer_valColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'divar_dakli_glb_sayer_val\' in table \'sazeh\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesazeh.divar_dakli_glb_sayer_valColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int divar_dakli_glb_tozi {
                get {
                    try {
                        return ((int)(this[this.tablesazeh.divar_dakli_glb_toziColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'divar_dakli_glb_tozi\' in table \'sazeh\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesazeh.divar_dakli_glb_toziColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string thvil_tarikh {
                get {
                    return ((string)(this[this.tablesazeh.thvil_tarikhColumn]));
                }
                set {
                    this[this.tablesazeh.thvil_tarikhColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int thvil_krshnas {
                get {
                    return ((int)(this[this.tablesazeh.thvil_krshnasColumn]));
                }
                set {
                    this[this.tablesazeh.thvil_krshnasColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Ismlk_idNull() {
                return this.IsNull(this.tablesazeh.mlk_idColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setmlk_idNull() {
                this[this.tablesazeh.mlk_idColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isshobh_idNull() {
                return this.IsNull(this.tablesazeh.shobh_idColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setshobh_idNull() {
                this[this.tablesazeh.shobh_idColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isfndsion_toziNull() {
                return this.IsNull(this.tablesazeh.fndsion_toziColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setfndsion_toziNull() {
                this[this.tablesazeh.fndsion_toziColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Issgf_sayrNull() {
                return this.IsNull(this.tablesazeh.sgf_sayrColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setsgf_sayrNull() {
                this[this.tablesazeh.sgf_sayrColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Issgf_toziNull() {
                return this.IsNull(this.tablesazeh.sgf_toziColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setsgf_toziNull() {
                this[this.tablesazeh.sgf_toziColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Issklt_toziNull() {
                return this.IsNull(this.tablesazeh.sklt_toziColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setsklt_toziNull() {
                this[this.tablesazeh.sklt_toziColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Issklt_sayrNull() {
                return this.IsNull(this.tablesazeh.sklt_sayrColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setsklt_sayrNull() {
                this[this.tablesazeh.sklt_sayrColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isdivar_dakli_glb_partitionNull() {
                return this.IsNull(this.tablesazeh.divar_dakli_glb_partitionColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setdivar_dakli_glb_partitionNull() {
                this[this.tablesazeh.divar_dakli_glb_partitionColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isdivar_dakli_glb_simaniNull() {
                return this.IsNull(this.tablesazeh.divar_dakli_glb_simaniColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setdivar_dakli_glb_simaniNull() {
                this[this.tablesazeh.divar_dakli_glb_simaniColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isdivar_dakli_glb_likaNull() {
                return this.IsNull(this.tablesazeh.divar_dakli_glb_likaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setdivar_dakli_glb_likaNull() {
                this[this.tablesazeh.divar_dakli_glb_likaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isdivar_dakli_glb_hblxNull() {
                return this.IsNull(this.tablesazeh.divar_dakli_glb_hblxColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setdivar_dakli_glb_hblxNull() {
                this[this.tablesazeh.divar_dakli_glb_hblxColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isdivar_dakli_glb_sofaliNull() {
                return this.IsNull(this.tablesazeh.divar_dakli_glb_sofaliColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setdivar_dakli_glb_sofaliNull() {
                this[this.tablesazeh.divar_dakli_glb_sofaliColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isdivar_dakli_glb_pomaNull() {
                return this.IsNull(this.tablesazeh.divar_dakli_glb_pomaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setdivar_dakli_glb_pomaNull() {
                this[this.tablesazeh.divar_dakli_glb_pomaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isdivar_dakli_glb_ajorNull() {
                return this.IsNull(this.tablesazeh.divar_dakli_glb_ajorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setdivar_dakli_glb_ajorNull() {
                this[this.tablesazeh.divar_dakli_glb_ajorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isdivar_dakli_glb_drywallNull() {
                return this.IsNull(this.tablesazeh.divar_dakli_glb_drywallColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setdivar_dakli_glb_drywallNull() {
                this[this.tablesazeh.divar_dakli_glb_drywallColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isdivar_dakli_glb_sayerNull() {
                return this.IsNull(this.tablesazeh.divar_dakli_glb_sayerColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setdivar_dakli_glb_sayerNull() {
                this[this.tablesazeh.divar_dakli_glb_sayerColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isdivar_dakli_glb_sayer_valNull() {
                return this.IsNull(this.tablesazeh.divar_dakli_glb_sayer_valColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setdivar_dakli_glb_sayer_valNull() {
                this[this.tablesazeh.divar_dakli_glb_sayer_valColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isdivar_dakli_glb_toziNull() {
                return this.IsNull(this.tablesazeh.divar_dakli_glb_toziColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setdivar_dakli_glb_toziNull() {
                this[this.tablesazeh.divar_dakli_glb_toziColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class sazehRowChangeEvent : global::System.EventArgs {
            
            private sazehRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public sazehRowChangeEvent(sazehRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public sazehRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591